version: '3'
services:
  mongo:
    container_name: mongodb-container
    image: mongo:5.0.14
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: api-container
    image: node:16
    working_dir: '/usr/src/blog-api'
    restart: always
    command: bash -c "npm install --only=prod && npm run start"
    volumes: 
      - ./dist/:/usr/src/blog-api/dist/
      - ./package.json:/usr/src/blog-api/package.json
    ports:
      - "3000:3000"
    links:
      - mongo